core:
  environment: "staging"
  lable: "subscription"
api:
  port: 8081
  health_port: 1488
  pprof_port: 6061
  metric_uri: "/metrics"
  health_uri: "/healthz"
  cokies_name: "TOKEN"
  cokies_domain: "localhost"
  token_expire_minutes: 60
  user_redis_cache: true
redis:
  use_redis: true
  address: "localhost"
  port: 6379
log:
  level: "info"
  disable_colors: false
  full_timestamp: true
postgresql:
  address: "localhost"
  port: 5432
  database: "go-subscription"
  username: "go"
  password: "secret"
  max_connections: 20
  log_level: "warning"
kafka:
  use_kafka: true
  address: "localhost"
  topic: "test.sub.go"
auth:
  url: "http://localhost:8080/api/valid"
